backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Homepage"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Titlel, name: title, widget: string }
          - {
              label: Herosection,
              name: herosection,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: "Subtitle", name: "subtitle", widget: "text" },
                  { label: "Description", name: "description", widget: "text" },
                  { label: Image, name: image, widget: image },
                ],
            }
          - {
              label: Aboutme,
              name: aboutme,
              widget: object,
              fields:
                [
                  { label: "TextLinks", name: "textlinks", widget: "text" },
                  { label: "TextRechts", name: "textrechts", widget: "text" },
                  { label: "TextUnten", name: "textunten", widget: "text" },
                  { label: Image, name: image, widget: image },
                ],
            }
          - {
              label: Training,
              name: training,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: "Subtitle", name: "subtitle", widget: "text" },
                  { label: "Description", name: "description", widget: "text" },
                  { label: Image, name: image, widget: image },
                ],
            }
          - {
              label: Beratung,
              name: beratung,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: "Subtitle", name: "subtitle", widget: "text" },
                  { label: "Description", name: "description", widget: "text" },
                  { label: Image, name: image, widget: image },
                ],
            }
          - {
              label: Coaching,
              name: coaching,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: "Subtitle", name: "subtitle", widget: "text" },
                  { label: "Description", name: "description", widget: "text" },
                  { label: Image, name: image, widget: image },
                ],
            }
          - {
              label: Supervision,
              name: supervision,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: "Subtitle", name: "subtitle", widget: "text" },
                  { label: "Description", name: "description", widget: "text" },
                  { label: Image, name: image, widget: image },
                ],
            }
